#!/usr/bin/env bash
# A Bash script that displays a user-oriented, hierarchical list of all running processes

ps -eo user,pid,ppid,%cpu,%mem,tty,cmd --sort=ppid | awk '
BEGIN {
  printf "%-15s %-6s %-6s %-6s %-6s %-10s %s\n", "USER", "PID", "PPID", "%CPU", "%MEM", "TTY", "COMMAND"
}
{
  indent = ""
  for (i = 0; i < $3 / 10; i++) indent = indent "  "
  printf "%-15s %-6s %-6s %-6s %-6s %-10s %s%s\n", $1, $2, $3, $4, $5, $6, indent, $7
}'
