#!/bin/bash

# Trap SIGTERM signal and respond with a custom message
trap "echo 'I am invincible!!!'" SIGTERM

# Infinite loop with message
while true
do
    echo "To infinity and beyond"
    sleep 2
done
