#!/usr/bin/env bash
# A Bash script that displays a message infinitely and handles SIGTERM by displaying a custom message

# Trap SIGTERM signal and respond with a custom message
trap "echo 'I am invincible!!!'" SIGTERM

# Infinite loop displaying a message every 2 seconds
while true
do
    echo "To infinity and beyond"
    sleep 2
done
cp 6-stop_me_if_you_can 67-stop_me_if_you_can
#!/usr/bin/env bash
# A Bash script that stops the 7-highlander process by sending a SIGTERM signal

pkill -f 7-highlander
